language: csharp
solution: rpg-data-engine.sln
mono: none
dotnet: 2.1.1
install:
  - nuget restore rpg-data-engine.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release rpg-data-engine.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DiceEngine.Tests/bin/Release/DiceEngine.Tests.dll